---
- name: Update all packages 
  yum:
    update_cache: yes
    name: '*'
    state: latest

- name: check if reboot is required
  shell: needs-restarting -r
  ignore_errors: true 
  register: reboot_required

- name: Reboot the server
  shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
  async: 1
  poll: 0
  ignore_errors: yes
  when: "'required' in reboot_required.stdout"

- name: Wait for server to come back up after reboot
  local_action: wait_for host={{ inventory_hostname }}
                port=22 state=started delay=10 timeout=320
  when: "'required' in reboot_required.stdout"

- debug:
    msg: "Server is back up and running"
