---
- name: Update all packages 
  yum:
    update_cache: yes
    name: '*'
    state: latest

- name: Check if reboot is required
  shell: needs-restarting -r
  ignore_errors: true 
  register: reboot_required

- name: Reboot the server is needed
  reboot:
    reboot_timeout: 300
  when: "'required' in reboot_required.stdout"